name: Build Web App

inputs:
  dotnet_version:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Setup .NET Core SDK ${{ inputs.dotnet_version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}
    - name: Install dependencies
      shell: bash
      run: dotnet restore
    - name: Build
      shell: bash
      run: dotnet build --configuration Release --no-restore