name: Whats My Ip Address
description: Gets the workflow runner ip address

outputs:
  ip:
    description: The workflow runner's ip address
    value: ${{ steps.whats-my-ip.outputs.ip }}

runs:
  using: composite

  steps:
    - name: Get Workflow runner IP
      shell: bash
      id: whats-my-ip
      run: |
        # Resolving IP Address

        # Maximum number of tries
        max_tries=5

        # Delay between tries in seconds
        delay=5

        for try in $(seq $max_tries); do
            # Make a GET request to the API
            response=$(curl -s https://api.ipify.org?format=json)

            # Extract the IP address from the JSON response 
            ip=$(echo $response | jq -r '.ip')

            # If the request was successful, print the IP and exit
            if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                stdbuf -o0 echo "IP Address: $ip"
                echo "ip=$ip" >> $GITHUB_OUTPUT 
                exit 0
            fi

            # If the request failed, wait and then try again
            stdbuf -o0 echo "Attempt $try failed, retrying in $delay seconds..."
            sleep $delay
        done

        # If we reach this point, all attempts have failed
        stdbuf -o0 echo "Failed to retrieve IP after $max_tries attempts."
        exit 1