name: Whats My Ip Address
description: Gets the workflow runner ip address

runs:
  using: composite

  steps:
    - name: Get Workflow runner IP
      shell: bash
      run: |
        echo "ip::$result" >> "$GITHUB_OUTPUT"

    - name: Validate IP
      shell: bash
      run: |
        if ! [[ $RUNNER_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "RUNNER_IP is not set to a valid IP address"
          echo "Runner IP: $RUNNER_IP"
          exit 1
        else
          echo "Runner IP: $RUNNER_IP"
        fi