name: Get GitHub Runner IP
description: Gets the IP Address for the currently running GitHub Runner and sets it as env variable "GITHUB_DEV"

runs:
  using: composite

  steps:
    - name: Get Workflow runner IP
      shell: bash
      run: |
        echo "RUNNER_IP=$(curl -s https://api.ipify.org?format=json | jq -r '.ip')" >> $GITHUB_ENV