name: 'Set Environment'

description: 'Determine the environment and set outputs'
inputs:
  environment:
    description: 'The target environment'
    required: false
    type: string
    default: 'dev'
    
outputs:
  environment: ${{ steps.var.outputs.environment }}
  branch: ${{ steps.var.outputs.branch }}
  release: ${{ steps.var.outputs.release }}
  checked-out-sha: ${{ steps.var.outputs.checked-out-sha }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - id: var
      run: |
        GIT_REF=${{ github.ref }}
        GIT_BRANCH=${GIT_REF##*/}
        INPUT=${{ inputs.environment }}
        ENVIRONMENT=${INPUT:-"dev"}
        RELEASE=${ENVIRONMENT,,}-`date +%Y-%m-%d`.${{ github.run_number }}
        CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
        echo "environment=${ENVIRONMENT,,}" >> $GITHUB_ENV
        echo "branch=$GIT_BRANCH" >> $GITHUB_ENV
        echo "release=${RELEASE}" >> $GITHUB_ENV
        echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_ENV
