name: Run Database Upgrader
description: Builds and runs the PlanTech database upgrader app

inputs:
  dotnet_version:
    required: true
    type: string
  dfe_service_id:
    required: true
    type: string
  dfe_project_name:
    required: true
    type: string  
  az_keyvault_database_connectionstring_name:
    required: true
    type: string  

env:
  KEYVAULT_NAME: ${{ env.INPUT_DFE_SERVICE_ID }}-${{ env.INPUT_DFE_PROJECT_NAME }}-kv
  # CONNECTION_STRING: Server=tcp:${{ locals.sql_server }}.database.windows.net,1433;Initial Catalog=${{ locals.sql_database }}-sqldb;Persist Security Info=False;User ID=${{ locals.sql_user_id }};Password=${{ locals.password }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

runs:
  using: composite

  steps:
    - name: Build database upgrader  
      uses: ./.github/actions/build-dotnet-app
      with:
        dotnet_version: ${{ inputs.dotnet_version }}  
        solution_filename: Dfe.PlanTech.DatabaseUpgrader.sln

    - name: Get connection string
      shell: bash
      run: |
        echo "CONNECTION_STRING=$(az keyvault secret show --name my-secret --vault-name ${{ env.KEYVAULT_NAME }} --query value -o tsv)" >> $GITHUB_ENV

    - name: Run database upgrader
      shell: bash
      run: dotnet ./build/Dfe.PlanTech.DatabaseUpgrader.dll ${{ CONNECTION_STRING }}