name: Run Database Upgrader
description: Builds and runs the PlanTech database upgrader app

inputs:
  dotnet_version:
    required: true
    type: string
  az_keyvault_name:
    required: true
    type: string  
  az_keyvault_database_connectionstring_name:
    required: true
    type: string  
  az_sql_database_server_name:
    required: true
    type: string  
  az_resource_group_name:
    required: true
    type: string 
    
env:
  ip_name: db-upgrader

runs:
  using: composite
  steps:
    - name: Build database upgrader  
      uses: ./.github/actions/build-dotnet-app
      with:
        dotnet_version: ${{ inputs.dotnet_version }}  
        solution_filename: Dfe.PlanTech.DatabaseUpgrader.sln

    - name: Get workflow IP address
      id: whats-my-ip
      uses: ./.github/actions/whats-my-ip-address
      
    - name: Add Azure firewall rules
      uses: ./.github/actions/azure-ip-whitelist
      with:
        ip_address: ${{ steps.whats-my-ip.outputs.ip }}
        verb: "add"
        az_keyvault_name: ${{ inputs.az_keyvault_name }}
        az_ip_name: ${{ env.ip_name }}
        az_resource_group: ${{ inputs.az_resource_group_name }}
        az_sql_database_server_name: ${{ inputs.az_sql_database_server_name }}

    - name: Get connection string
      id: get-db-connection-string
      uses: ./.github/actions/azure-get-db-connectionstring
      with:
        az_keyvault_name: ${{ env.KEYVAULT_NAME }}
        az_keyvault_database_connectionstring_name: ${{ env.az_keyvault_database_connectionstring_name }}

    - name: Run database upgrader
      shell: bash
      run: dotnet ./build/Dfe.PlanTech.DatabaseUpgrader.dll -c "${{ steps.get-db-connection-string.outputs.connection_string }}"

    - name: Remove Azure firewall rules
      if: always()
      uses: ./.github/actions/azure-ip-whitelist
      with:
        ip_address: ${{ steps.whats-my-ip.outputs.ip }}
        verb: "remove"
        az_keyvault_name: ${{ inputs.az_keyvault_name }}
        az_ip_name: ${{ env.ip_name }}
        az_resource_group: ${{ inputs.az_resource_group_name }}
        az_sql_database_server_name: ${{ inputs.az_sql_database_server_name }}
