name: Run Cypress E2E tests
description: Run E2E tests using Cypress

inputs:
  url:
    required: true
    type: string
  dsi_url:
    required: true
    type: string
  dsi_username:
    required: true
    type: string
  dsi_password:
    required: true
    type: string
  start:
    required: false
    type: string
    description: Start command for Cypress

runs:
  using: composite

  steps:
    - name: Build and test project
      uses: cypress-io/github-action@v5
      with:
        start: ${{ inputs.start }}
        config: url=${{ inputs.url }},DSiUrl=${{ inputs.dsi_url }},Username=${{ inputs.dsi_username }},Password=${{ inputs.dsi_password }}
        project:  ./tests/Dfe.PlanTech.Web.E2ETests/
        wait-on: 'https://localhost:8081'
        browser: chrome
      
    - name: Store screenshots on test failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ./tests/Dfe.PlanTech.Web.E2ETests/cypress/screenshots
          
    - name: Store videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: ./tests/Dfe.PlanTech.Web.E2ETests/cypress/videos
