name: Run Cypress E2E tests
description: Run E2E tests using Cypress

inputs:
  url:
    required: true
    type: string
  dsi_url:
    required: true
    type: string
  dsi_username:
    required: true
    type: string
  dsi_password:
    required: true
    type: string
  start:
    required: false
    type: string
    description: Start command for Cypress

runs:
  using: composite

  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "latest"

    - name: Install Dependencies
      shell: bash
      working-directory: ./tests/Dfe.PlanTech.Web.E2ETests/
      run: npm install

    - name: Create Cypress config
      shell: bash
      run: |
        echo "{\"URL\": \"${{inputs.url}}\", \"DSiUrl\": \"${{inputs.dsi_url}}\", \"Username\": \"${{inputs.dsi_username}}\", \"Password\": \"${{inputs.dsi_password}}\" }" >cypress.env.json 
      working-directory: ./tests/Dfe.PlanTech.Web.E2ETests/

    - name: Run the tests
      shell: bash
      working-directory: ./tests/Dfe.PlanTech.Web.E2ETests/
      run: npx cypress run --e2e --config chromeWebSecurity=false --browser chromium

    - name: Store screenshots on test failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: ./tests/Dfe.PlanTech.Web.E2ETests/cypress/screenshots
          
    - name: Store videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: ./tests/Dfe.PlanTech.Web.E2ETests/cypress/videos
