name: Run Unit Tests

runs:
  using: composite

  steps:
    - name: Test
      shell: bash
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}