name: Run Unit Tests
description: Runs the unit tests and publishes them to the workflow runs 

inputs:
  solution_filename:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Run CS unit tests
      shell: bash
      run: dotnet test ${{ inputs.solution_filename }} --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./TestResults/ --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=test-results.trx" || true

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "latest"

    - name: Install Dependencies
      shell: bash
      run: npm install

    - name: Run JS unit tests
      shell: bash
      run: npm test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: 'false'

    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: ./junit.xml    # Path to test results
        reporter: jest-junit        # Format of test results
        fail-on-error: 'false'