name: Azure IP Whitelist
description: Add or remove an IP Address to the Azure KV + SQL whitelist

inputs:
  ip_address:
    required: true
    type: string
  verb:
    required: true
    type: choice
    options:
      - "add"
      - "remove"
  resource_group:
    required: true
    type: string
  keyvault_name:
    required: true
    type: string
  name:
    type: string
    default: "github_action"
  sql_database_server_name:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Add to whitelist
      if: ${{ inputs.verb == 'add' }}
      shell: bash
      run: |
        az keyvault network-rule add --resource-group ${{ inputs.resource_group }} --name ${{ inputs.keyvault_name }} --ip-address ${{ inputs.ip_address }}
        az sql server firewall-rule create --resource-group ${{ inputs.resource_group }} --server ${{ inputs.az_sql_database_server_name }} --name ${{ inputs.name }} --start-ip-address ${{ inputs.ip_address }} --end-ip-address ${{ inputs.ip_address }}
    
    - name: Remove from whitelist
      if: ${{ inputs.verb == 'remove' }}
      shell: bash
      run: |
        az keyvault network-rule remove --resource-group ${{ inputs.resource_group }} --name ${{ inputs.keyvault_name }} --ip-address ${{ inputs.ip_address }}
        az sql server firewall-rule delete --resource-group ${{ inputs.resource_group }} --server ${{ inputs.az_sql_database_server_name }} --name ${{ inputs.name }}