name: Get DB connection string
description: Gets DB connection string from Azure Keyvault

inputs:
  az_keyvault_database_connectionstring_name:
    required: true
    type: string
  az_keyvault_name:
    required: true
    type: string
    
outputs:
  connection_stirng:
    description: DB connection string
    value: ${{ steps.get-connection-string.outputs.connection_string }}

runs:
  using: composite
  steps:
    - name: Get connection string
      id: get-connection-string
      shell: bash
      run: |
        connection_string=$(az keyvault secret show --name ${{ inputs.az_keyvault_database_connectionstring_name }} --vault-name ${{ inputs.az_keyvault_name }} --query value -o tsv)
        echo "::add-mask::$connection_string"
        echo "connection_string=$connection_string" >> $GITHUB_OUTPUT
        echo "connection string is $connection_string"