name: Build DotNet App
description: Sets up .Net for specified version and builds application

inputs:
  solution_filename:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Install dependencies
      shell: bash
      run: dotnet restore ${{ inputs.solution_filename }}
    - name: Build
      shell: bash
      run: dotnet build ${{ inputs.solution_filename }} --configuration Release --no-restore --output ./build