name: Remove firewall exclusions
description: Removes firewall exclusions to SQL Server and/or KeyVault

inputs:
  az_keyvault_name:
    required: false
    type: string  
  az_sql_database_server_name:
    required: false
    type: string  
  az_resource_group_name:
    required: true
    type: string 
  ip_address:
    required: true
    type: string
  
runs:
  using: composite

  steps:
    - name: Remove Azure Firewall Rule to SQL Server
      if: inputs.az_sql_database_server_name != ''
      shell: bash
      run: |
        az sql server firewall-rule delete --resource-group ${{ inputs.az_resource_group_name }} --server ${{ inputs.az_sql_database_server_name }} --name github-workflow &> /dev/null

    - name: Remove Azure Firewall Rule to Keyvault
      if: inputs.az_keyvault_name != ''
      shell: bash
      run: | 
        az keyvault network-rule remove --resource-group ${{ inputs.az_resource_group_name }} --name ${{ inputs.az_keyvault_name }} --ip-address ${{ inputs.ip_address }} &> /dev/null