name: Concept Workflow to harden pipeline
on:
  pull_request:
    branches:
      - "feat/pipeline-hardening"
  workflow_dispatch:
    inputs:
      option:
        description: 'Choose an option'
        required: true
        default: 'option1'
        options: ['tst', 'staging', 'production']

jobs:
  set-env:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Set env Complete
        run: echo "Set env Complete"

  tag-release:
    name: Job 2
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - name: tag-release
        run: echo "Tag and release Complete"

  upgrade-db:
    name: Job 3
    runs-on: ubuntu-latest
    needs: tag-release
    steps:
      - name: Upgrade DB Complete
        run: echo "Job Complete"

  deploy-image:
    name: Fourth Job
    runs-on: ubuntu-latest
    needs: upgrade-db
    steps:
      - name: Deploy Image Complete
        run: echo "Deployment Complete"

  promote-build:
    name: promote to env
    runs-on: ubuntu-latest
    needs: deploy-image
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Conditional Step
        run: |
          if [ "${{ github.event.inputs.option }}" == "tst" ]; then
            echo "Test environment selected";
          elif [ "${{ github.event.inputs.option }}" == "staging" ]; then
            echo "Staging environment selected";
          elif [ "${{ github.event.inputs.option }}" == "production" ]; then
            echo "Production environment selected";
          else
            echo "Invalid option selected";
            exit 1;
          fi