name: Build & Deploy .NET Azure Function App

on:
    workflow_call:
        inputs:
            environment:
                type: string
                required: true

concurrency:
    # group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
    group: ${{ github.workflow }}-${{ github.run_id }} # TODO: Remove after testing!
    cancel-in-progress: true

env:
    DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:

    build:

        runs-on: windows-latest
        name: Build & Deploy .NET Azure Function App
        environment: ${{ inputs.environment }}
        env:
            AZURE_FUNCTIONAPP_NAME: "${{ secrets.AZ_ENVIRONMENT }}plantechcontentfulfunction"
        
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v3
  
            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
  
            - name: Install Dependencies
              shell: pwsh
              run: dotnet restore ./src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj
  
            - name: Build Azure Function App
              shell: pwsh
              run: dotnet publish ./src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj --configuration Release --no-restore --output ./build

            - name: Azure CLI Login
              uses: ./.github/actions/azure-login
              with:
                az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
                az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
                az_client_id: ${{ secrets.AZ_CLIENT_ID }}
                az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
            
            - name: Deploy Azure Function App
              uses: Azure/functions-action@v1
              id: fa
              with:
                app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                package: ./build