name: Build and commit web assets (JS + CSS)

on:
  pull_request:
    branches: [ "main" ]
  
jobs:
    build-web-resouces:
        name: Build JS and SCSS files
        runs-on: ubuntu-22.04
        defaults:
          run:
            shell: bash
            working-directory: ./scrc/Dfe.PlanTech.Web.Node/
    
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: ${{ github.ref }}
    
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
              node-version: "latest"
    
          - name: Install Dependencies
            run: npm install
    
          - name: Build
            run: npm run build
          
          - name: Commit and push changes
            run: |
              if [[ `git status --porcelain` ]]; then
                git commit -am "Updated JS + CSS files"
                git push
                echo "Commited changes"
              else
                echo "No changes to commit"
              fi
    