name: Build & Deploy .NET Azure Function App

on:
    workflow_call: # TODO: Called from matrix-deploy OR ran as an independent workflow on push to main/development?
        inputs:
            environment:
                type: string
                required: true

concurrency:
    group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
    cancel-in-progress: true

env:
    DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:

    build:

        runs-on: ubuntu-22.04
        name: Build .NET Azure Function App
        
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
                cache: false
              env:
                DOTNET_INSTALL_DIR: "/usr/share/dotnet"
                DOTNET_CLI_TELEMETRY_OPTOUT: true

            - name: Install Dependencies
              shell: bash
              run: dotnet restore ./src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj

            - name: Build Azure Function App
              shell: bash
              run: dotnet publish ./src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj --configuration Release --no-restore --output ./build

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: .dotnet-azure-function-app
                path: ./build

    deploy:

        runs-on: ubuntu-22.04
        name: Deploy .NET Azure Function App
        needs: build
        environment: ${{ inputs.environment }}
        env:
            AZURE_FUNCTIONAPP_NAME: "${{ secrets.AZ_ENVIRONMENT }}plantechcontentfulfunction"
        
        steps:

            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                name: .dotnet-azure-function-app
            
            - name: Deploy Azure Function App
              uses: Azure/functions-action@v1
              with:
                app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                package: .
                publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # TODO: Investigate obtaining 'publish-profile' via Terraform