name: Build & Deploy .NET Azure Function App

# on:
#     workflow_call: # TODO: Called from matrix-deploy OR ran as an independent workflow on push to main/development?
#         inputs:
#             environment:
#                 type: string
#                 required: true

on:                                                                   # TODO: Remove after testing!
    pull_request:                                                     # TODO: Remove after testing!
        branches: ["development"]                                     # TODO: Remove after testing!
        paths:                                                        # TODO: Remove after testing!
            - 'src/**'                                                # TODO: Remove after testing!
            - '.github/workflows/build-and-deploy-azure-function.yml' # TODO: Remove after testing!

concurrency:
    # group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
    group: ${{ github.workflow }}-${{ github.run_id }} # TODO: Remove after testing!
    cancel-in-progress: true

env:
    DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:

    build:

        runs-on: windows-latest
        name: Build .NET Azure Function App
        
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Install Dependencies
              shell: pwsh
              run: dotnet restore ./src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj

            - name: Build Azure Function App
              shell: pwsh
              run: dotnet publish ./src/Dfe.PlanTech.AzureFunctions/Dfe_PlanTech_AzureFunctions.csproj --configuration Release --no-restore --output ./build

            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                name: .dotnet-azure-function-app
                path: ./build

    deploy:

        runs-on: windows-latest
        name: Deploy .NET Azure Function App
        needs: build
        # environment: ${{ inputs.environment }}
        environment: "Dev" # TODO: Remove after testing!
        env:
            AZURE_FUNCTIONAPP_NAME: "${{ secrets.AZ_ENVIRONMENT }}plantechcontentfulfunction"
        
        steps:

            - name: Download Artifact
              uses: actions/download-artifact@v2
              with:
                name: .dotnet-azure-function-app

            - name: Azure CLI Login
              uses: ./.github/actions/azure-login
              with:
                az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
                az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
                az_client_id: ${{ secrets.AZ_CLIENT_ID }}
                az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
            
            - name: Deploy Azure Function App
              uses: Azure/functions-action@v1
              id: fa
              with:
                app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                package: .