name: Clear user data from DB
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "What environment to clear"
        required: true
        type: environment

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  disallow-prod-message:
    if: inputs.environment == 'Production'
    name: Disallow production message
    runs-on: ubuntu-latest

    steps:
      - name: Disallow production message
        run: echo "This action is not allowed in production"

  clear-db:
    if: inputs.environment != 'Production'
    environment: ${{ inputs.environment }}
    name: Clear user data from DB
    runs-on: ubuntu-latest
    env:
      az_keyvault_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-kv
      az_keyvault_database_connectionstring_name: ${{ secrets.AZ_KEYVAULT_DATABASE_CONNECTIONSTRING_NAME }}
      az_sql_database_server_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
      az_resource_group_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
      SQL_IP_NAME: github-action-clear-user-data

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login with AZ
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}
          az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}

      - name: Get workflow IP address
        id: whats-my-ip
        uses: ./.github/actions/whats-my-ip-address

      - name: Add Azure firewall rules
        uses: ./.github/actions/azure-ip-whitelist
        with:
          ip_address: ${{ steps.whats-my-ip.outputs.ip }}
          verb: "add"
          az_keyvault_name: ${{ env.az_keyvault_name }}
          az_ip_name: ${{ env.SQL_IP_NAME }}
          az_resource_group: ${{ env.az_resource_group_name}}
          az_sql_database_server_name: ${{ env.az_sql_database_server_name }}

      - name: Get connection string
        id: get-connection-string
        uses: ./.github/actions/azure-get-db-connectionstring
        with:
          az_keyvault_name: ${{ env.az_keyvault_name }}
          az_keyvault_database_connectionstring_name: ${{ env.az_keyvault_database_connectionstring_name }}

      - name: Execute stored procedure
        uses: azure/sql-action@v2.2
        with:
          connection-string: ${{ steps.get-connection-string.outputs.connection_string }}
          path: "./.github/scripts/clear-user-data-from-db.sql"

      - name: Remove Azure firewall rules
        if: always()
        uses: ./.github/actions/azure-ip-whitelist
        with:
          ip_address: ${{ steps.whats-my-ip.outputs.ip }}
          verb: "remove"
          az_keyvault_name: ${{ env.az_keyvault_name }}
          az_ip_name: ${{ env.SQL_IP_NAME }}
          az_resource_group: ${{ env.az_resource_group_name}}
          az_sql_database_server_name: ${{ env.az_sql_database_server_name }}
