name: Code PR Check 

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  build-test-app:  
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build web app  
        uses: ./.github/actions/build-web-app
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}  

  test-ui:
    name: Run UI E2E tests
    runs-on: ubuntu-latest
    
    steps:   
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Run Cypress tests
        uses: ./.github/actions/run-e2e-tests

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Build docker image
        uses: ./.github/actions/build-docker-image 