name: Code PR Check 

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}
  
jobs:
  build-test-app:  
    name: Build and run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build web app  
        uses: ./.github/actions/build-dotnet-app
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}  
          solution_filename: plan-technology-for-your-school.sln

      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests