name: Code PR Check

on:
  push:
    branches: ["main", "development"]
    paths:
      - "src/**"
      - "tests/**"
  pull_request:
    branches: ["main", "development"]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/code-pr-check.yml"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  build-test-web-app:
    name: Build and run unit tests
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install dotnet coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Install SonarCloud scanners
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install latest JDK
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Start SonarCloud scanner
        run: |
          dotnet-sonarscanner begin \
          /k:"DFE-Digital_plan-technology-for-your-school" \
          /o:"dfe-digital" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
          /d:sonar.coverage.exclusions=src/**/Program.cs,src/Dfe.PlanTech.Web/gulpfile.js,src/Dfe.PlanTech.Web/wwwroot/** \
          /d:sonar.issue.ignore.multicriteria=e1 \
          /d:sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S6602 \
          /d:sonar.issue.ignore.multicriteria.e1.resourceKey=src/**/*.cs

      - name: Build web app
        uses: ./.github/actions/build-dotnet-app
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}
          solution_filename: plan-technology-for-your-school.sln

      - name: Run tests
        run: dotnet test plan-technology-for-your-school.sln --verbosity normal --collect:"XPlat Code Coverage"

      - name: Merge test results
        run: dotnet-coverage merge -f xml -o "coverage.xml" -s "coverage.settings.xml" -r coverage.cobertura.xml

      - name: End SonarCloud Scanner
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.xml
