name: Create & Tag Release

on:
  workflow_call:

jobs:
  create-tag-release:
    runs-on: ubuntu-22.04
    name: Tag & Create Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Dependencies
        run: |
          npm i -g npm@latest
          npm i npx@10
          npm i @semantic-release/commit-analyzer@12
          npm i @semantic-release/release-notes-generator@12
          npm i @semantic-release/github@10

      - name: Verify Integrity of Installed Dependencies
        run: npm audit signatures

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@23
