name: Create & Tag Release

on:
  workflow_call:
  pull_request:
    branches:
      ['development']
      
jobs:
  create-tag-release:
    runs-on: ubuntu-22.04
    name: Tag & Create Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install and audit dependency signatures
        working-directory: ./.github/semver-release
        run: |
          npm ci
          npm audit signatures

      - name: Create Release
        working-directory: ./.github/semver-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
