name: Run E2E Testing on a Deployed Environment

on:
    workflow_call:
      inputs:
        environment:
          type: string
          required: true

concurrency:
    group: ${{ github.workflow }}-${{ github.event.inputs.environment }}-e2e-deployed
    cancel-in-progress: true

jobs:

    set-env:

        runs-on: ubuntu-22.04
        name: Set Environment (E2E Test)
        outputs:
            environment: ${{ steps.var.outputs.environment }}
        
        steps:
            
            - id: var
              run: |
                ENVIRONMENT=${{ inputs.environment }}
                echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT

    clear-database:

        runs-on: ubuntu-22.04
        name: Clear Database on ${{ needs.set-env.outputs.environment }}
        environment: ${{ needs.set-env.outputs.environment }}
        needs: [set-env]
        env:
            az_keyvault_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-kv
            az_keyvault_database_connectionstring_name: ${{ secrets.AZ_KEYVAULT_DATABASE_CONNECTIONSTRING_NAME }}
            az_sql_database_server_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
            az_resource_group_name: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
            SQL_IP_NAME: e2e-tests-clear-db
        
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Azure CLI Login
              uses: ./.github/actions/azure-login
              with:
                az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
                az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
                az_client_id: ${{ secrets.AZ_CLIENT_ID }}
                az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
            
            - name: Get Workflow IP Address
              id: what-is-my-ip
              uses: ./.github/actions/whats-my-ip-address
            
            - name: Add Azure Firewall Rules
              uses: ./.github/actions/azure-ip-whitelist
              with:
                ip_address: ${{ steps.what-is-my-ip.outputs.ip }}
                verb: "add"
                az_keyvault_name: ${{ env.az_keyvault_name }}
                az_ip_name: ${{ env.SQL_IP_NAME }}
                az_resource_group: ${{ env.az_resource_group_name}}
                az_sql_database_server_name: ${{ env.az_sql_database_server_name }}

            - name: Get Connection String
              id: get-connection-string
              uses: ./.github/actions/azure-get-db-connectionstring
              with:
                az_keyvault_name: ${{ env.az_keyvault_name }}
                az_keyvault_database_connectionstring_name: ${{ env.az_keyvault_database_connectionstring_name }}

            - name: Execute Stored Procedure
              uses: azure/sql-action@v2.2
              with:
                connection-string: ${{ steps.get-connection-string.outputs.connection_string }}
                path: "./.github/scripts/drop-establishment-data.sql"
            
            - name: Remove Azure Firewall Rules
              if: always()
              uses: ./.github/actions/azure-ip-whitelist
              with:
                ip_address: ${{ steps.what-is-my-ip.outputs.ip }}
                verb: "remove"
                az_keyvault_name: ${{ env.az_keyvault_name }}
                az_ip_name: ${{ env.SQL_IP_NAME }}
                az_resource_group: ${{ env.az_resource_group_name}}
                az_sql_database_server_name: ${{ env.az_sql_database_server_name }}
    
    run-e2e-tests:
        
        runs-on: ubuntu-22.04
        name: Run E2E Tests on ${{ needs.set-env.outputs.environment }}
        environment: ${{ needs.set-env.outputs.environment }}
        needs: [set-env, clear-database]
        
        steps:
            
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Cypress Testing
              uses: ./.github/actions/run-e2e-tests
              with:
                url: ${{ secrets.AZ_FRONTDOOR_URL }}
                dsi_url: ${{ secrets.DSI_URL }}
                dsi_username: ${{ secrets.DSI_USERNAME }}
                dsi_password: ${{ secrets.DSI_PASSWORD }}