name: Run E2E Tests

on:
  pull_request:
    paths: 
      - 'terraform/**'
      - '.github/**'
            
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-22.04

    env:
        PROJECT_PATH: ./src/Dfe.PlanTech.Web/Dfe.PlanTech.Web.csproj 
        KEYVAULT_NAME: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}-kv
        RESOURCE_GROUP: ${{ secrets.AZ_ENVIRONMENT }}${{ secrets.DFE_PROJECT_NAME }}
        SQL_IP_NAME: e2e-tests-pr

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ secrets.AZ_TENANT_ID }}
          az_subscription_id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.AZ_CLIENT_ID }}
          az_client_secret: ${{ secrets.AZ_CLIENT_SECRET }}
  
      - name: Get workflow IP address
        id: whats-my-ip
        uses: ./.github/actions/whats-my-ip-address
    
      - name: Add Azure firewall rules
        uses: ./.github/actions/azure-ip-whitelist
        with:
          ip_address: ${{ steps.whats-my-ip.outputs.ip }}
          verb: "add"
          az_keyvault_name: ${{ env.KEYVAULT_NAME }}
          az_ip_name: ${{ env.SQL_IP_NAME }}
          az_resource_group: ${{ env.RESOURCE_GROUP}}
          az_sql_database_server_name: ${{ env.RESOURCE_GROUP }}

      - name: Build docker image
        shell: bash
        run: docker build -f ./src/Dfe.PlanTech.Web/Dockerfile -t plan-tech:latest ./

      - name: Generate dev https cert
        shell: bash
        run: |
          dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p https_password
          dotnet dev-certs https --trust

      - name: Run docker image
        shell: bash
        run: docker run --publish 8081:8081 -e ASPNETCORE_ENVIRONMENT=Production -e KeyVaultName=s190d01-plantech-kv -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORT=8001 -e ASPNETCORE_Kestrel__Certificates__Default__Password="https_password" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ plan-tech:latest

      - name: Cypress tests
        uses: ./.github/actions/run-e2e-tests
        with:
          url: https://localhost:8081
          dsi_url: ${{ secrets.DSI_URL }}
          dsi_username: ${{ secrets.DSI_USERNAME }}
          dsi_password: ${{ secrets.DSI_PASSWORD }}
      
      - name: Remove Azure firewall rules
        if: always()
        uses: ./.github/actions/azure-ip-whitelist
        with:
          ip_address: ${{ steps.whats-my-ip.outputs.ip }}
          verb: "add"
          az_keyvault_name: ${{ env.KEYVAULT_NAME }}
          az_ip_name: ${{ env.SQL_IP_NAME }}
          az_resource_group: ${{ env.RESOURCE_GROUP}}
          az_sql_database_server_name: ${{ env.RESOURCE_GROUP }}  
  