name: Multi stage build & deploy 

on:
  workflow_dispatch:
  push:
    branches: ["main", "Development"]
    paths:
      - 'src/**'
      - '.github/workflows/matrix-deploy.yml'
    
jobs:
  deploy-to-environments:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ Dev, Tst, Staging, Production ]
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit
