name: Build & deploy to environment

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Manual publish to which environment
        options:
          - Staging
          - Production
  push:
    branches: [ "feat/pipeline-hardening" ]
  

jobs:
  deploy-to-environments:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ dev ]
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit
    
  deploy-to-staging:
    needs: deploy-to-environments
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "will deploy to staging on manual dispatch trigger here"
#    uses: ./.github/workflows/build-and-deploy.yml
#    with:
#      environment: Staging
#    secrets: inherit
      
  deploy-to-prod:
    needs: deploy-to-staging
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.name == 'Production' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo "will deploy to prod on manual dispatch when Production choice is selected"
#    uses: ./.github/workflows/build-and-deploy.yml
#    with:
#      environment: Production
#    secrets: inherit
