name: Multi stage build & deploy 

on:
  workflow_dispatch:
  push:
    branches: ["main", "development"]
    paths:
      - 'src/**'
      - '.github/workflows/matrix-deploy.yml'
    
jobs:

  get-branch:
    runs-on: ubuntu-22.04
    name: Get Target Branch Name
    outputs:
      branch: ${{ steps.var.outputs.branch }}
    steps:
      - id: var
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT

  create-and-publish-image:
    name: Create & Publish Image
    uses: ./.github/workflows/build-image.yml
    secrets: inherit

  check-for-terraform-changes:
    needs: create-and-publish-image
    runs-on: ubuntu-22.04
    name: Check for Terraform File Changes
    outputs:
      run_terraform_deploy: ${{ steps.terraform_changes.outputs.run_terraform_deploy }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 2

      - name: Check for Terraform File Changes
        id: terraform_changes
        run: |
          LAST_COMMIT_SHA=${{ github.sha }}
          PENULTIMATE_COMMIT_SHA=$(git rev-list -n 1 --skip 1 $LAST_COMMIT_SHA | tail -n 1)
          echo "Last commit SHA: $LAST_COMMIT_SHA and Penultimate commit SHA: $PENULTIMATE_COMMIT_SHA"
          changed_files="$(git diff --name-only $PENULTIMATE_COMMIT_SHA $LAST_COMMIT_SHA)"
          echo "Changed files:"
          echo "$changed_files"

          if [[ "$changed_files" =~ terraform/container-app ]]; then
            echo "Terraform files have changed. Running Terraform deploy..."
            echo "run_terraform_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "No Terraform file changes in terraform/container-app. Skipping Terraform deploy."
            echo "run_terraform_deploy=false" >> $GITHUB_OUTPUT
          fi
          
  deploy-terraform-for-dev-and-test:
    needs: check-for-terraform-changes
    name: Deploy Terraform Infrastructure for Dev & Test
    if: ${{ needs.check-for-terraform-changes.outputs.run_terraform_deploy == 'true' }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ Dev, Tst ]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit

  deploy-to-dev-and-test:
    needs: [get-branch, create-and-publish-image, check-for-terraform-changes, deploy-terraform-for-dev-and-test]
    name: Deployment to Dev & Test
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [Dev, Tst]
    uses: ./.github/workflows/deploy-image.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit

  deploy-terraform-for-staging:
    needs: [deploy-to-dev-and-test, check-for-terraform-changes]
    name: Deploy Terraform Infrastructure for staging
    if: ${{ needs.check-for-terraform-changes.outputs.run_terraform_deploy == 'true' &&  needs.get-branch.outputs.branch == 'main' }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ Staging ]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit
    
  deploy-to-staging:
    needs: [get-branch, create-and-publish-image, deploy-to-dev-and-test, deploy-terraform-for-staging] 
    name: Deployment to Staging
    if: ${{ needs.get-branch.outputs.branch == 'main' }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [Staging ]
    uses: ./.github/workflows/deploy-image.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit
    
  deploy-terraform-for-production:
    needs: [ deploy-to-dev-and-test, check-for-terraform-changes, deploy-to-staging, deploy-terraform-for-staging ]
    name: Deploy Terraform Infrastructure for production
    if: ${{ needs.check-for-terraform-changes.outputs.run_terraform_deploy == 'true' && needs.get-branch.outputs.branch == 'main' }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ Production ]
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit

  deploy-to-production:
    needs: [ get-branch, create-and-publish-image, deploy-to-dev-and-test, deploy-to-staging, deploy-terraform-for-staging, deploy-terraform-for-production ]
    name: Deployment to Production
    if: ${{ needs.get-branch.outputs.branch == 'main' }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ Production ]
    uses: ./.github/workflows/deploy-image.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit