name: Multi stage build & deploy 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'

jobs:
  deploy-to-environments:
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        target: [ dev, tst, staging ]
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit
