name: Multi-Stage Build & Deploy (Azure Function)

on:
  workflow_dispatch:
  push:
    branches: ["main", "development"]
    paths:
      - "src/Dfe.PlanTech.AzureFunctions/**"
      - ".github/workflows/matrix-deploy-azure-function.yml"
      - ".github/workflows/build-azure-function.yml"
      - ".github/workflows/deploy-azure-function.yml"
  pull_request: # TODO: REMOVE AFTER TESTING
    branches: ["development"] # TODO: REMOVE AFTER TESTING
    paths: # TODO: REMOVE AFTER TESTING
      - ".github/workflows/matrix-deploy-azure-function.yml" # TODO: REMOVE AFTER TESTING
      - ".github/workflows/build-azure-function.yml" # TODO: REMOVE AFTER TESTING
      - ".github/workflows/deploy-azure-function.yml" # TODO: REMOVE AFTER TESTING

jobs:
  set-env:
    runs-on: ubuntu-22.04
    name: Set Environment (Matrix Deploy Azure Function)
    outputs:
      branch: ${{ steps.var.outputs.branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - id: var
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT

  build-azure-function:
    name: Build Azure Function
    uses: ./.github/workflows/build-azure-function.yml

  deploy-azure-function-for-dev-test:
    needs: [set-env, build-azure-function]
    name: Deploy Azure Function
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        target: [Dev, Tst]
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      environment: ${{ matrix.target }}
    secrets: inherit

  deploy-azure-function-for-staging:
    needs: [set-env, build-azure-function, deploy-azure-function-for-dev-test]
    name: Deploy Azure Function (Staging)
    if: ${{ needs.set-env.outputs.branch == 'main' }}
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      environment: Staging
    secrets: inherit

  deploy-azure-function-for-production:
    needs:
      [
        set-env,
        build-azure-function,
        deploy-azure-function-for-dev-test,
        deploy-azure-function-for-staging,
      ]
    name: Deploy Azure Function (Production)
    if: ${{ needs.set-env.outputs.branch == 'main' }}
    uses: ./.github/workflows/deploy-azure-function.yml
    with:
      environment: Production
    secrets: inherit
