name: Validate Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  build-test-app:  
    name: Build and test     
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build web app  
        uses: ./.github/actions/build-web-app
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}  
      - name: Run unit tests
        uses: ./.github/actions/run-unit-tests
 
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build docker image
        uses: ./.github/actions/build-docker-image 