name: QA Visualisation Workflow


on:
  push:
    branches:
      - qa-view-spike

jobs:
  generate_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Graphviz
        run: |
          sudo apt-get install graphviz 
          
      - name: Install Microsoft ODBC
        run: sudo ACCEPT_EULA=Y apt-get install msodbcsql17 -y
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          
      - name: Install pyodbc
        run: |
          pip install pyodbc
    
      - name: Install dependencies
        run: |
          pip install graphviz
          
      - name: Run data script
        run: |
          python ./.github/scripts/qa-data.py
        env:
          SQL_CONNECTION_STRING: ${{ secrets.QA_VIZ_CONNECTION_STRING_DEV }}
          
      - name: List data files
        run: |
          ls -l ./data
            
      - name: Run Visaulisation Script
        run: python ./.github/scripts/qa-visualisations.py 
        
      - name: Upload image
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: qa-visualisations
          path: ./visualisations
        
      - name: Call Teams Webhook
        run: |
            curl -X POST -H 'Content-Type: application/json' -d '{"text": "New Visualisations Available: https://github.com/DFE-Digital/plan-technology-for-your-school/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}' ${{ secrets.PLANTECH_TEAMS_WEBHOOK }}
