on:
  push:
    branches:
      - qa-view-spike

jobs:
  generate_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Graphviz
        run: |
          sudo apt-get install graphviz 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          
          
      - name: Install dependencies
        run: |
          pip install graphviz
      - name: Run Script
        run: python ./.github/scripts/test.py 
        
      - name: upload image
        uses: actions/upload-artifact@v3
        with:
          name: qa-visualisations
          path: ./.github/scripts/test