name: Run E2E Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - 'terraform/**'

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
    build-docker-image:
        name: Run E2E tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2    

            - name: Checkout and run E2E tests
              uses: ./.github/actions/run-e2e-tests