name: Terraform PR Test

on: 
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'terraform/**'
      - '.github/**'
  pull_request:
    paths: 
      - 'terraform/**'
      - '.github/**'

jobs:
  validate-terraform:  
    name: Validate Terraform Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
    
      - name: Validate Terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: terraform
          config-file: .terraform-docs.yml
          output-file: terraform-configuration.md
          output-method: inject
          fail-on-diff: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
            name: terraform-config
            path: terraform/terraform-configuration.md
