name: Terraform PR Test

on: 
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'terraform/**'
      - '.github/**'
  pull_request:
    paths: 
      - 'terraform/**'
      - '.github/**'

jobs:
  validate-terraform:  
    name: Validate Terraform 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.TF_WORKING_DIRECTORY}}
    steps:
      - name: Validate Terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: terraform
          config-file: .terraform-docs.yml
          output-method: print
          fail-on-diff: true